FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="${PATH}:/root/.local/bin"
RUN apt-get -yq update && apt-get install --no-install-recommends -yq festival festvox-us-slt-hts python3-pip gnuradio sox && pip install --break-system-packages sigmf
COPY siggen.py /siggen.py
RUN /siggen.py --int_count 1 --samp_rate 100000 --siggen am --sample_file /tmp/test && rm -f /tmp/test
CMD ["/siggen.py"]
