name: CI Test
on: [push, pull_request]
jobs:
  ci-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          version: 1.8.3
      - name: Install poetry and dependencies
        run: |
          apt-get -yq update && apt-get -yq libcurand\* libcublas\* && \
          git submodule init && \
          git submodule update && \
          poetry config virtualenvs.create false && \
          poetry install  
